brew "sheldon"
brew "colima"

cask "font-0xproto-nerd-font"
cask "karabiner-elements"
cask "clipy"
cask "whatsapp"
cask "arc"
cask "discord"
cask "google-japanese-ime"
cask "linearmouse"
cask "slack"
