#!/usr/bin/env perl

# LaTeX処理エンジンの設定
$latex = 'platex -synctex=1 -halt-on-error -interaction=nonstopmode %O %S';
$pdflatex = 'pdflatex -synctex=1 -halt-on-error -interaction=nonstopmode %O %S';
$lualatex = 'lualatex -synctex=1 -halt-on-error -interaction=nonstopmode %O %S';

# BibTeXとMakeindex
$bibtex = 'pbibtex %O %B';
$makeindex = 'mendex %O -o %D %S';

# DVI -> PDF変換
$dvipdf = 'dvipdfmx %O -o %D %S';
$dvips = 'dvips %O -o %D %S';
$ps2pdf = 'ps2pdf %O %S %D';

# PDFビューアー設定
$pdf_previewer = 'open -a Skim';
$pdf_update_method = 4;

# 出力形式（3: dvi -> pdf）
$pdf_mode = 3;

# 自動ビルド設定
$max_repeat = 5;

# 中間ファイルのクリーンアップ
$clean_ext = 'synctex.gz aux bbl blg dvi fdb_latexmk fls idx ilg ind log nav out snm toc vrb';
