# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json

git:
  branchPrefix: "nurazon59/"
  paging:
    externalDiffCommand: "difft --color=always"
  mainBranches:
    - "main"
    - "master"
    - "develop"
    - "dev"
  parseEmoji: true

gui:
  nerdFontsVersion: "3"
  border: "single"
  authorColors:
    "renovate[bot]": "#737994"
  theme:
    activeBorderColor:
      - "#ca9ee6"
      - bold
    inactiveBorderColor:
      - "#737994"
    optionsTextColor:
      - "#8caaee"
    selectedLineBgColor:
      - "#414559"
    cherryPickedCommitBgColor:
      - "#51576d"
    cherryPickedCommitFgColor:
      - "#ca9ee6"
    unstagedChangesColor:
      - "#e78284"
    defaultFgColor:
      - "#c6d0f5"
    searchingActiveBorderColor:
      - "#e5c890"

os:
  editPreset: "nvim-remote"

confirmOnQuit: true
quitOnTopLevelReturn: true

customCommands:
  - key: "<c-s>"
    context: "global"
    command: "gh repo view --web"
    description: "GitHubでリポジトリを開く"
  - key: "<c-r>"
    command: "gh pr create --fill-first --web"
    context: "global"
    loadingText: "Creating pull request on GitHub"
    description: "GitHubでPRを作成"