# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json

git:
  branchPrefix: 'nurazon59/'
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never
  mainBranches:
    - 'main'
    - 'master'
    - 'develop'
    - 'dev'
  parseEmoji: true

gui:
  nerdFontsVersion: '3'
  border: 'single'
  authorColors:
    'renovate[bot]': '#737994'
  theme:
    activeBorderColor:
      - '#3e8fb0'
      - bold
    inactiveBorderColor:
      - '#6e6a86'
    searchingActiveBorderColor:
      - '#ea9a97'
      - bold
    optionsTextColor:
      - '#9ccfd8'
    selectedLineBgColor:
      - '#3e8fb0'
    inactiveViewSelectedLineBgColor:
      - '#393552'
      - bold
    cherryPickedCommitFgColor:
      - '#2a273f'
    cherryPickedCommitBgColor:
      - '#ea9a97'
    markedBaseCommitFgColor:
      - '#9ccfd8'
    markedBaseCommitBgColor:
      - '#f6c177'
    unstagedChangesColor:
      - '#eb6f92'
    defaultFgColor:
      - '#e0def4'

os:
  editPreset: 'nvim-remote'

quitOnTopLevelReturn: true

customCommands:
  - key: '<c-s>'
    context: 'global'
    command: 'gh repo view --web'
    description: 'GitHubでリポジトリを開く'
  - key: '<c-r>'
    command: 'gh pr create --fill-first --web'
    context: 'global'
    loadingText: 'Creating pull request on GitHub'
    description: 'GitHubでPRを作成'
