return {
  "stevearc/aerial.nvim",
  dependencies = {
    "nvim-treesitter/nvim-treesitter",
    "nvim-tree/nvim-web-devicons",
  },
  keys = {
    { "<leader>o", "<cmd>AerialToggle<CR>", desc = "アウトライン表示切替" },
    { "{", "<cmd>AerialPrev<CR>", desc = "前のシンボルへ", mode = "n" },
    { "}", "<cmd>AerialNext<CR>", desc = "次のシンボルへ", mode = "n" },
  },
  opts = {
    layout = {
      max_width = { 40, 0.2 },
      min_width = 30,
      default_direction = "right",
    },
    filter_kind = {
      "Class",
      "Constructor",
      "Function",
      "Method",
      "Interface",
      "Module",
      "Struct",
      "Enum",
    },
    attach_mode = "window",
    close_on_select = false,
    highlight_on_hover = true,
    autojump = false,
    icons = {
      Array = " ",
      Boolean = " ",
      Class = " ",
      Constant = " ",
      Constructor = " ",
      Enum = " ",
      EnumMember = " ",
      Event = " ",
      Field = " ",
      File = " ",
      Function = " ",
      Interface = " ",
      Key = " ",
      Method = " ",
      Module = " ",
      Namespace = " ",
      Null = "ﳠ ",
      Number = " ",
      Object = " ",
      Operator = " ",
      Package = " ",
      Property = " ",
      String = " ",
      Struct = " ",
      TypeParameter = " ",
      Variable = " ",
    },
  },
}
