[worktree]
basedir = '~/src'
auto_mkdir = true

[naming]
template = '{{.Host}}/{{.Owner}}/{{.Repository}}-{{.Hash}}'

[naming.sanitize_chars]
'/' = '-'
':' = '-'

[cd]
auto_cd_on_add = false
launch_shell = true

[finder]
preview = true

[ui]
icons = true
tilde_home = true

[[repository_settings]]
repository = "/**"
setup_commands = ['if [ "$(git config --bool --get core.sparseCheckout 2>/dev/null || echo false)" = true ]; then git sparse-checkout disable; fi']
