[tools]
"aqua:suzuki-shunsuke/ghalint" = "latest"
"cargo:mergiraf" = "latest"
"go:github.com/d-kuro/gwq/cmd/gwq" = "latest"
"go:github.com/nurazon59/ghmux" = "latest"
"go:github.com/nurazon59/rport" = "latest"
"go:github.com/nurazon59/nippo" = "latest"
"go:github.com/jorgerojas26/lazysql" = "latest"
"npm:@mermaid-js/mermaid-cli" = "latest"
"npm:@openai/codex" = "latest"
"npm:@playwright/cli" = "latest"
"npm:ctx7" = "latest"
"npm:difit" = "latest"
"npm:docusaurus" = "latest"
"npm:oxfmt" = "latest"
"npm:typescript" = "latest"
act = "latest"
aqua = "2.60.2"
aws = "latest"
bun = "1.3.14"
deno = "2.9.2"
ecspresso = "latest"
github-cli = "latest"
go = "1.26.5"
golangci-lint = "latest"
goreleaser = "latest"
lefthook = "latest"
node = "26.5.0"
pipx = "latest"
pinact = "latest"
pnpm = "latest"
python = "3.14.6"
rust = "1.96.1"
terraform = "1.15.8"
uv = "latest"
yarn = "latest"
opencode = "latest"

[settings]
idiomatic_version_file_enable_tools = ["python"]
experimental = true
# minimum_release_age = "7d"
lockfile = true
