# Alacritty設定ファイル
# kittyの設定を移植

[window]
# ウィンドウ設定
padding.x = 10
padding.y = 10
opacity = 0.95
dynamic_padding = true
decorations = "buttonless" # macOS: タイトルバーなし
startup_mode = "Windowed"
dynamic_title = true

[window.dimensions]
columns = 160
lines = 50

[scrolling]
history = 10000
multiplier = 3

[font]
# フォント設定
size = 12.0

[font.normal]
family = "0xProto Nerd Font Mono"
style = "Regular"

[font.bold]
family = "0xProto Nerd Font Mono"
style = "Bold"

[font.italic]
family = "0xProto Nerd Font Mono"
style = "Italic"

[font.bold_italic]
family = "0xProto Nerd Font Mono"
style = "Bold Italic"

[cursor]
# カーソル設定
style.shape = "Beam"
style.blinking = "Off"
unfocused_hollow = true

[bell]
# ベル設定
animation = "EaseOutExpo"
duration = 0
color = "#ffffff"

[selection]
# 選択設定
save_to_clipboard = true

[colors]
# Tokyo Night カラースキーム
[colors.primary]
background = "#1a1b26"
foreground = "#c0caf5"

[colors.cursor]
text = "#1a1b26"
cursor = "#c0caf5"

[colors.selection]
text = "#c0caf5"
background = "#33467c"

[colors.normal]
black = "#15161e"
red = "#f7768e"
green = "#9ece6a"
yellow = "#e0af68"
blue = "#7aa2f7"
magenta = "#bb9af7"
cyan = "#7dcfff"
white = "#a9b1d6"

[colors.bright]
black = "#414868"
red = "#f7768e"
green = "#9ece6a"
yellow = "#e0af68"
blue = "#7aa2f7"
magenta = "#bb9af7"
cyan = "#7dcfff"
white = "#c0caf5"

[mouse]
# マウス設定
hide_when_typing = true

[[mouse.bindings]]
mouse = "Right"
action = "PasteSelection"

[keyboard]
# キーバインド設定

[[keyboard.bindings]]
key = "C"
mods = "Command"
action = "Copy"

[[keyboard.bindings]]
key = "V"
mods = "Command"
action = "Paste"

[[keyboard.bindings]]
key = "N"
mods = "Command"
action = "CreateNewWindow"

[[keyboard.bindings]]
key = "W"
mods = "Command"
action = "Quit"

[[keyboard.bindings]]
key = "T"
mods = "Command"
action = "CreateNewWindow"

[[keyboard.bindings]]
key = "Plus"
mods = "Command"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "Minus"
mods = "Command"
action = "DecreaseFontSize"

[[keyboard.bindings]]
key = "Key0"
mods = "Command"
action = "ResetFontSize"

[[keyboard.bindings]]
key = "F"
mods = "Command"
action = "ToggleFullscreen"

[[keyboard.bindings]]
key = "Key1"
mods = "Command"
chars = "\u001b[1;9P"

[[keyboard.bindings]]
key = "Key2"
mods = "Command"
chars = "\u001b[1;9Q"

[[keyboard.bindings]]
key = "Key3"
mods = "Command"
chars = "\u001b[1;9R"

[[keyboard.bindings]]
key = "Key4"
mods = "Command"
chars = "\u001b[1;9S"

[[keyboard.bindings]]
key = "Key5"
mods = "Command"
chars = "\u001b[15;9~"

[[keyboard.bindings]]
key = "Key6"
mods = "Command"
chars = "\u001b[17;9~"

[[keyboard.bindings]]
key = "Key7"
mods = "Command"
chars = "\u001b[18;9~"

[[keyboard.bindings]]
key = "Key8"
mods = "Command"
chars = "\u001b[19;9~"

[[keyboard.bindings]]
key = "Key9"
mods = "Command"
chars = "\u001b[20;9~"

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\n"

# tmux: Cmd+Dで縦分割
[[keyboard.bindings]]
key = "D"
mods = "Command"
chars = "\u001bd"

# tmux: Cmd+Shift+Dで横分割
[[keyboard.bindings]]
key = "D"
mods = "Command|Shift"
chars = "\u001bD"

[env]
# 環境変数
TERM = "xterm-256color"
