# espanso match file

j For a complete introduction, visit the official docs at: https://espanso.org/docs/

# You can use this file to define the base matches (aka snippets)
# that will be available in every application when using espanso.

# Matches are substitution rules: when you type the "trigger" string
# it gets replaced by the "replace" string.

# yaml-language-server: $schema=https://raw.githubusercontent.com/espanso/espanso/dev/schemas/match.schema.json

matches:
  - trigger: "/must"
    replace: "![must](https://img.shields.io/badge/review-MUST-red)"
  - trigger: "/want"
    replace: "![want](https://img.shields.io/badge/review-WANT-orange)"
  - trigger: "/imo"
    replace: "![imo](https://img.shields.io/badge/review-IMO-yellow)"
  - trigger: "/nits"
    replace: "![nits](https://img.shields.io/badge/review-NITS-lightgrey)"
  - trigger: "/ask"
    replace: "![ask](https://img.shields.io/badge/review-ASK-mediumpurple)"
  - trigger: "/good"
    replace: "![good](https://img.shields.io/badge/review-Good-green)"
  - trigger: "/tweet"
    replace: "![tweet](https://img.shields.io/badge/review-Tweet-blue)"
  - trigger: "/fyi"
    replace: "![fyi](https://img.shields.io/badge/review-FYI-lightblue)"
