# ================================================
# misc
# ================================================

set -g default-shell $SHELL
if-shell "command -v reattach-to-user-namespace >/dev/null 2>&1" \
  'set-option -g default-command "reattach-to-user-namespace -l $SHELL"' \
  'set-option -g default-command "$SHELL"'

# OSC 52でalacrittyにクリップボードを渡す
set -s set-clipboard on

# 履歴サイズを5000行に設定
set -g history-limit 5000

# ================================================
# appearance
# ================================================

# 256色
set -g default-terminal "tmux-256color"
# set -ag terminal-overrides ",alacritty:RGB"
set -ag terminal-overrides ",xterm-256color:RGB"
set -ag terminal-overrides ",xterm-ghostty:RGB"

# enable visual notification
set-window-option -g monitor-activity on
set -g visual-activity on

# refresh rate (default 15sec)
set -g status-interval 5

set -g focus-events on

source-file "~/.config/tmux/style.tmux"

# ================================================
# keybind
# ================================================

# prefixキーをC-aに変更する
set -g prefix C-t

# C-bのキーバインドを解除する
unbind C-b

# キーストロークのディレイを減らす
set -sg escape-time 1

# 設定ファイルをリロードする
bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded!"

bind f display-popup -E -w 70% -h 70% -d '#{pane_current_path}'

# copy mode with vi keybind
set-window-option -g mode-keys vi
bind v copy-mode
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
bind-key -T copy-mode-vi i send-keys -X cancel

# ウィンドウとペインの番号を1から開始
set -g base-index 1
setw -g pane-base-index 1

# ウィンドウを閉じた時に番号を詰める
set -g renumber-windows on

# fish側で常時更新するためtmuxの自動リネームは無効化
set-window-option -g automatic-rename off

# ================================================
# mouse
# ================================================

# マウス操作の有効化
set-option -g mouse on

# ================================================
# plugins
# ================================================

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-pain-control'
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @resurrect-capture-pane-contents 'on'
set -g @continuum-restore 'on'
set -g @continuum-save-interval '1'

tpm_version="3.1.0"
tpm_dir="~/.config/tmux/plugins/tpm"
tpm_repo_url="https://github.com/tmux-plugins/tpm.git"
if "test ! -d ~/.config/tmux/plugins/tpm" \
     "run 'git clone --depth=1 -b v3.1.0 https://github.com/tmux-plugins/tpm.git ~/.config/tmux/plugins/tpm && ~/.config/tmux/plugins/tpm/bindings/install_plugins'"

run "~/.config/tmux/plugins/tpm/tpm"

# ================================================
# smart-splits.nvim + tmux 連携
# ================================================

# @pane-is-vim はsmart-splitsが自動設定
bind-key -n C-h if -F "#{@pane-is-vim}" "send-keys C-h" "select-pane -L"
bind-key -n C-j if -F "#{@pane-is-vim}" "send-keys C-j" "select-pane -D"
bind-key -n C-k if -F "#{@pane-is-vim}" "send-keys C-k" "select-pane -U"
bind-key -n C-l if -F "#{@pane-is-vim}" "send-keys C-l" "select-pane -R"




# ================================================
# Passthrough
# ================================================
bind m send-keys C-t m
