# Dotterテスト用の最小設定

[helpers]

[minimal]
depends = []

[minimal.files]
# テスト用に少数のファイルのみ
"root/.gitconfig" = "~/.gitconfig"
"root/.gitignore" = "~/.gitignore"
"config/.config/starship.toml" = "~/.config/starship.toml"

[minimal.variables]