[helpers]

[default]
depends = []

[default.files]
Brewfile = "~/Brewfile"
Makefile = "~/Makefile"
config = { target = "~/.config", type = "symbolic", recurse = true }
root = { target = "~/", type = "symbolic", recurse = true }

[default.variables]

[settings]
default_target_type = "automatic"
