[helpers]

[default]
depends = []

[default.files]
"root/.gitconfig" = "~/.gitconfig"
"root/.gitignore" = "~/.gitignore"
"root/.zshrc" = "~/.zshrc"
"root/.tool-versions" = "~/.tool-versions"

"root/.claude" = "~/.claude"
"root/.gemini" = "~/.gemini"
"root/.codex" = "~/.codex"

"config/.config/nvim" = "~/.config/nvim"
"config/.config/gh" = "~/.config/gh"
"config/.config/gh-dash" = "~/.config/gh-dash"
"config/.config/mise" = "~/.config/mise"
"config/.config/sheldon" = { target = "~/.config/sheldon", type = "symbolic" }
"config/.config/yazi" = "~/.config/yazi"
"config/.config/lazygit" = "~/.config/lazygit"
"config/.config/direnv" = "~/.config/direnv"
"config/.config/github-copilot" = "~/.config/github-copilot"
"config/.config/any-script-mcp" = "~/.config/any-script-mcp"
"config/.config/starship.toml" = "~/.config/starship.toml"

[default.variables]

[macos]
depends = ["default"]

[macos.files]
"config/.config/aerospace" = "~/.config/aerospace"
"config/.config/borders" = "~/.config/borders"
"config/.config/karabiner" = "~/.config/karabiner"
"config/.config/kitty" = "~/.config/kitty"
"config/.config/linearmouse" = "~/.config/linearmouse"
"config/.config/sketchybar" = "~/.config/sketchybar"

[macos.variables]
os = "macos"

[tex]
depends = []

[tex.files]
"root/.latexmkrc" = "~/.latexmkrc"
"config/.config/tex" = "~/.config/tex"

[tex.variables]

