# Starship configuration

format = """
${custom.git_repo}\
$directory\
$git_branch\
$git_status\
$line_break\
$character"""

[custom.git_repo]
when = true
require_repo = true
command = 'git rev-parse --show-toplevel | sed -e "s,$(ghq root)/\(github\.com/\)\?,,"'
style = 'bold cyan'
format = '[$output]($style) '

[directory]
truncation_length = 3
truncate_to_repo = true
style = 'cyan'
format = '[$path]($style) '
repo_root_format = ''

[git_branch]
format = "[$symbol$branch]($style) "
style = "bold purple"

[git_status]
format = '([$all_status$ahead_behind]($style))'
style = ""
conflicted = "[~${count}](bold red) "
ahead = "[⇡${count}](bold green) "
behind = "[⇣${count}](bold red) "
diverged = "[⇕⇡${ahead_count}⇣${behind_count}](bold red) "
untracked = "[?${count}](blue) "
stashed = "[*${count}](cyan) "
modified = "[!${count}](yellow) "
staged = "[+${count}](green) "
renamed = "[»${count}](blue) "
deleted = "[✘${count}](red) "

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"

[aws]
disabled = true
